### ISSUE TITLE
Not able to use with Crypto.scrypt in NodeJS

### ISSUE THREAD

**Issue by backspacerhino** [firebase/scrypt#2]
Hi,

I am using NodeJS and would like to the built in Crypto module that has scrypt() function to hash password so that I can compare them to firebase saved passwords but I am getting a different hash.

This is the signature used to hash using firebase

`scrypt {key} {salt} {saltSeparator} {rounds} {memcost} [-P]`

but I want to use this function

`crypto.scrypt('secret', 'salt', 64, (err, derivedKey) => {
  if (err) throw err;
  console.log(derivedKey.toString('hex'));
});`

Can you please explain to me how to setup crypto.scrypt with the **hash parameters** from firebase so that I am able to use the build in module and not clone this repo in order to use it?

Thanks

**Comment by kmcnellis** [comment]
Sorry, Firebase doesn't use the standard Scrypt Algorithm. We use just the derived key (taken from the password, salt, and salt separator), and then do an extra round of AES using it and the project-level signing key.  

You can take a look at the function [scryptenc_buf_saltlen](https://github.com/firebase/scrypt/commit/7734f081a584993e7c9785f2534499100f2d1013#diff-e99b0389e5e911d83c252c69d0b4a871R94), and where it's [called](https://github.com/firebase/scrypt/commit/7734f081a584993e7c9785f2534499100f2d1013#diff-2045016cb90d1e65d71c2407a2570927R157) 

We also do a layer of base64 [encoding/decoding](https://github.com/firebase/scrypt/commit/7734f081a584993e7c9785f2534499100f2d1013#diff-2045016cb90d1e65d71c2407a2570927R111)

The outline of it is: 

1. Decrypt the User's salt, and Project's base64_signer_key and base64_salt_separator from base64

1. Run crypto.scrypt function with the parameters:
password = User's password
salt = User's salt + salt_separator
options.N = 2 ^ mem_cost
options.r = rounds
options.p = 1

1. Then take the returned derived Key, and run AES on it, with the key being the derived key, and the input being the project's signer_key (decrypted from base64)

2. Encode the result using base64

**Comment by y-a-n-n** [comment]
HI @kmcnellis! Sorry to hijack this old thread, but I'm trying to implement the functionality of this libary in Java and am running into an issue: my scrypt hash (i.e. the derived key) of the provided password matches between the two implementations, but the AES encryption step returns different results. In particular, I'm confused as to why the derived key length is 64 bytes when decoded, given AES accepts a maximum key length of 32 bytes... 

Is it just the first 32 bytes that are used? I can't seem to get the same result using:

```
final byte[] keyVal = Base64.decodeBase64(derivedKey.getBytes(CHARSET));
Key key = new SecretKeySpec(keyVal, 0, 32, "AES");
```

Thanks!

**Comment by y-a-n-n** [comment]
Also curious if you have any input on what AES parameters to use for this step; I'm currently using `final Cipher c = Cipher.getInstance("AES/CTR/NoPadding");`

**Comment by kmcnellis** [comment]
Try checking on your base64 decoding. I'm not sure why you are encoding/decoding the derived key between generating it and creating the AES key.  Firebase's scrypt implementation only does base64 encoding in the beginning & final steps, for input & to output the result. 

If that doesn't help, maybe check on your SecretKeySpec and IvParameterSpec.  I'm not familiar with java's crypto, but this blog proved useful to me in explaining the steps: https://www.mkammerer.de/blog/aes-ctr-encryption-with-java/

Firebase's scrypt does the same steps as standard scrypt's `scryptenc_buf` (with the different derived key).  It does include truncating the derived key to a length of 32 bytes, then running it though crypto_aes_key_expand with a length of 256 bits/32 bytes (14 rounds).  
[see diff](https://github.com/firebase/scrypt/commit/7734f081a584993e7c9785f2534499100f2d1013#diff-e99b0389e5e911d83c252c69d0b4a871R112)
```
key_enc_exp = crypto_aes_key_expand(key_enc, 32)) // truncate 
AES = crypto_aesctr_init(key_enc_exp, 0)
crypto_aesctr_stream(AES, inbuf, &outbuf[0], inbuflen)
```

`crypto_aes_key_expand` [(code)](https://github.com/Tarsnap/scrypt/blob/6ff3bf117db48c9f50cfd75d3be5223998a7cc61/libcperciva/crypto/crypto_aes.c#L100), calls openssl's `AES_set_encrypt_key(key, (int)(len * 8), kexp);` [(code)](https://github.com/openssl/openssl/blob/master/crypto/aes/aes_core.c#L639)

`crypto_aesctr_init` is written by scrypt, but appears to be standard AES in CTR mode [(code)](https://github.com/Tarsnap/scrypt/blob/06bafaf7216d4f231a2b5595dd64ba2f04e5e473/libcperciva/crypto/crypto_aesctr.c#L24), called by `scryptenc_buf` with a nonce of 0.

**Comment by y-a-n-n** [comment]
EDIT: Ignore the below, I got it working :) Thanks for all your help!

Thanks, that's very helpful.

I can see that `crypto_aesctr_init` is called with a `uint64_t` value of 0, which in Java is equivalent to (from the blog you linked):
``` 
final byte[] nonce = ByteBuffer.allocate(8).putLong(0).array();
```
I think the final missing piece for me is the value of the IV; the blog you linked recommends something like this:
```
// IV is a nonce followed by a counter (starting at 0). The IV is always 128 bit long.
// IV in hex looks for example: a2591afec0b2575c50943f2100000000
//                              |nonce                  |counter
byte[] iv = new byte[128 / 8];
System.arraycopy(nonce, 0, iv, 0, nonce.length);
```
Which basically just uses an IV of all zeroes if my nonce is zero, and seems consistent with this code in `crypto_aesctr_init`:

```
/* Initialize values. */
stream->key = key;
stream->nonce = nonce;
stream->bytectr = 0;
```
Is my understanding that the IV is essentially equivalent to the `nonce` and `bytectr` values correct? Or is there some other value I should be using for the IV? Using all zeroes doesn't seem to return the expected result.

In case you are interested, my code is [here ](https://github.com/SmartMoveSystems/firebase-scrypt-java/blob/master/src/main/java/com/smartmovesystems/hashcheck/FirebaseScrypt.java)

**Comment by kmcnellis** [comment]
Just for my curiosity, what fixed it?

**Comment by kmcnellis** [comment]
Also, if you'd like, I'll add a link to your implementation from the README - just let me know, or file a PR (You would need to put up an OSS a license on your code, though)

**Comment by y-a-n-n** [comment]
In the end, passing in the IV/nonce of all zeros produced the right result, but my test was comparing the wrong expected value...

Please feel free to add a link to our implementation, thanks!

https://github.com/SmartMoveSystems/firebase-scrypt-java

I've now added a licence and updated the README.
